blank_issues_enabled: false
contact_links:
  - name: Ask a question / Start a discussion
    url: https://github.com/frasermolyneux/portal-repository-func/discussions
    about: For questions, ideas, and general discussion
