name: "Copilot Coding Agent Task"
description: "A minimal form to request work for GitHub Copilot Coding Agent."
title: "[Copilot] <short, action-oriented title>"
labels:
  - copilot-coding-agent
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Provide a short summary and clear acceptance criteria. When the issue is ready, assign it to Copilot.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What should be built or fixed and why (1–3 sentences).
      placeholder: "Add endpoint to export Map Popularity data for dashboards"
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: Checklist of outcomes that prove this is done.
      value: |
        - [ ] Behavior matches the Summary
        - [ ] Basic edge cases handled
        - [ ] Tests added/updated as needed
      render: markdown
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes / links (optional)
      description: Relevant files, designs, or references.
      placeholder: |
        - src/.../SomeFile.cs
        - Related doc or issue link
    validations:
      required: false
